# Generated by Django 3.2.6 on 2023-06-13 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('name', models.TextField(primary_key=True, serialize=False)),
                ('home_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_address', to='locations.location')),
                ('outside_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outside_address', to='locations.location')),
            ],
        ),
    ]
