# Generated by Django 3.2.6 on 2023-06-08 13:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('name', models.TextField(primary_key=True, serialize=False)),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=9, validators=[django.core.validators.MinValueValidator(1.23776), django.core.validators.MaxValueValidator(1.47066)])),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=11, validators=[django.core.validators.MinValueValidator(103.61751), django.core.validators.MaxValueValidator(104.0436)])),
            ],
        ),
    ]
