# Generated by Django 3.2.6 on 2023-06-15 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meetup',
            old_name='meetup_id',
            new_name='meetup',
        ),
        migrations.RenameField(
            model_name='participate',
            old_name='meetup_id',
            new_name='meetup',
        ),
    ]
