# Generated by Django 3.1 on 2022-09-01 03:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MRT',
            fields=[
                ('lat', models.DecimalField(decimal_places=8, default=0, max_digits=9, validators=[django.core.validators.MinValueValidator(1.23776), django.core.validators.MaxValueValidator(1.47066)])),
                ('lon', models.DecimalField(decimal_places=8, default=0, max_digits=11, validators=[django.core.validators.MinValueValidator(103.61751), django.core.validators.MaxValueValidator(104.0436)])),
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('code', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Mall',
            fields=[
                ('lat', models.DecimalField(decimal_places=8, default=0, max_digits=9, validators=[django.core.validators.MinValueValidator(1.23776), django.core.validators.MaxValueValidator(1.47066)])),
                ('lon', models.DecimalField(decimal_places=8, default=0, max_digits=11, validators=[django.core.validators.MinValueValidator(103.61751), django.core.validators.MaxValueValidator(104.0436)])),
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('stores', models.IntegerField(default=0)),
                ('halals', models.IntegerField(default=0)),
                ('desirability', models.DecimalField(decimal_places=4, default=0.0, max_digits=7, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('mrt', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='malls', to='locations.mrt')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Halal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=8, default=0, max_digits=9, validators=[django.core.validators.MinValueValidator(1.23776), django.core.validators.MaxValueValidator(1.47066)])),
                ('lon', models.DecimalField(decimal_places=8, default=0, max_digits=11, validators=[django.core.validators.MinValueValidator(103.61751), django.core.validators.MaxValueValidator(104.0436)])),
                ('name', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=100)),
                ('mall', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='locations.mall')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
