# Generated by Django 3.1 on 2022-08-28 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='halal',
            name='mall',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='locations.mall'),
        ),
        migrations.AlterField(
            model_name='mall',
            name='halals',
            field=models.IntegerField(default=0),
        ),
    ]
