# Generated by Django 3.1 on 2022-09-01 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='halal',
            name='mall',
            field=models.ForeignKey(db_column='halal_places', default=None, on_delete=django.db.models.deletion.CASCADE, to='locations.mall'),
        ),
        migrations.AlterField(
            model_name='mall',
            name='mrt',
            field=models.ForeignKey(db_column='malls', default=None, on_delete=django.db.models.deletion.CASCADE, to='locations.mrt'),
        ),
    ]
