# Generated by Django 3.1 on 2022-08-31 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_auto_20220828_0940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mrt',
            name='desirability',
        ),
        migrations.RemoveField(
            model_name='mrt',
            name='malls',
        ),
        migrations.AddField(
            model_name='mall',
            name='mrt',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='locations.mrt'),
        ),
    ]
